name: cinder_nested
description: Nested widget support for Cinder.
version: 1.0.0-dev.1
repository: https://github.com/eukalpia/cinder

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  cinder: ^1.0.0-dev.1

dependency_overrides:
  cinder:
    path: ../..
