name: cinder_riverpod
description: Riverpod support for cinder - A reactive caching and data-binding framework
version: 0.0.1
homepage: https://cinder.dev
repository: https://github.com/norbert515/cinder

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  cinder: ^0.2.0
  riverpod: ^2.5.1
  meta: ^1.3.0

dev_dependencies:
  test: ^1.25.6
