name: cinder_riverpod
description: Riverpod integration for Cinder.
version: 1.0.0-dev.1
homepage: https://github.com/eukalpia/cinder
repository: https://github.com/eukalpia/cinder

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  cinder: ^1.0.0-dev.1
  riverpod: ^3.3.2
  meta: ^1.15.0

dev_dependencies:
  test: ^1.25.6

dependency_overrides:
  cinder:
    path: ../..
