name: cinder_provider
description: Provider integration for cinder
version: 0.0.1
repository: https://github.com/norbert515/cinder

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  meta: ^1.17.0
  cinder: ^0.2.0
  cinder_nested: ^0.0.1
