name: cinder_provider
description: Provider-style dependency injection and state management for Cinder.
version: 1.0.0-dev.2
repository: https://github.com/eukalpia/cinder

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  meta: ^1.17.0
  cinder: ^1.0.0-dev.2
  cinder_nested: ^1.0.0-dev.2

dev_dependencies:
  test: ^1.25.6

dependency_overrides:
  cinder:
    path: ../..
  cinder_nested:
    path: ../cinder_nested
