import '../image/image_cleanup.dart';

/// Validates terminal-native image protocol payloads before they reach the
/// host terminal.
///
/// Application text must never be passed to this API. Valid payloads are
/// generated by Cinder's Kitty, iTerm2, and Sixel encoders. The validator is a
/// defense-in-depth boundary that rejects extra ANSI/OSC/DCS commands appended
/// to an otherwise valid image sequence.
final class TerminalImagePayloadValidator {
  const TerminalImagePayloadValidator._();

  static final RegExp _kittyHeader = RegExp(r'^[A-Za-z0-9_,=.+-]*$');
  static final RegExp _base64 = RegExp(r'^[A-Za-z0-9+/]*={0,2}$');
  static final RegExp _itermArguments = RegExp(r'^[A-Za-z0-9_=/+;,.% -]*$');

  static bool isValid(String payload, ImageProtocol protocol) {
    if (payload.isEmpty) return false;
    switch (protocol) {
      case ImageProtocol.kitty:
        return _isValidKitty(payload);
      case ImageProtocol.iterm2:
        return _isValidITerm2(payload);
      case ImageProtocol.sixel:
        return _isValidSixel(payload);
      case ImageProtocol.unicodeBlocks:
        return false;
    }
  }

  static String requireValid(String payload, ImageProtocol protocol) {
    if (!isValid(payload, protocol)) {
      throw ArgumentError.value(
        '<${payload.length} code units>',
        'payload',
        'Invalid or mixed terminal image protocol payload for ${protocol.name}.',
      );
    }
    return payload;
  }

  static bool _isValidKitty(String payload) {
    const start = '\x1b_G';
    const end = '\x1b\\';
    var offset = 0;
    var chunks = 0;

    while (offset < payload.length) {
      if (!payload.startsWith(start, offset)) return false;
      final terminator = payload.indexOf(end, offset + start.length);
      if (terminator < 0) return false;
      final body = payload.substring(offset + start.length, terminator);
      if (body.isEmpty || _containsControl(body)) return false;

      final separator = body.indexOf(';');
      if (separator < 0 || body.indexOf(';', separator + 1) >= 0) return false;
      final header = body.substring(0, separator);
      final encoded = body.substring(separator + 1);
      if (!_kittyHeader.hasMatch(header) || !_base64.hasMatch(encoded)) {
        return false;
      }
      if (!header.split(',').every(_isValidKittyParameter)) return false;

      chunks++;
      offset = terminator + end.length;
    }
    return chunks > 0 && offset == payload.length;
  }

  static bool _isValidKittyParameter(String parameter) {
    final equals = parameter.indexOf('=');
    if (equals <= 0 || equals == parameter.length - 1) return false;
    final key = parameter.substring(0, equals);
    final value = parameter.substring(equals + 1);
    return RegExp(r'^[A-Za-z][A-Za-z0-9]*$').hasMatch(key) &&
        RegExp(r'^[A-Za-z0-9.+-]+$').hasMatch(value);
  }

  static bool _isValidITerm2(String payload) {
    const prefix = '\x1b]1337;File=';
    if (!payload.startsWith(prefix)) return false;

    int terminatorLength;
    if (payload.endsWith('\x07')) {
      terminatorLength = 1;
    } else if (payload.endsWith('\x1b\\')) {
      terminatorLength = 2;
    } else {
      return false;
    }

    final body = payload.substring(
      prefix.length,
      payload.length - terminatorLength,
    );
    if (_containsControl(body)) return false;
    final separator = body.indexOf(':');
    if (separator <= 0 || body.indexOf(':', separator + 1) >= 0) return false;
    final arguments = body.substring(0, separator);
    final encoded = body.substring(separator + 1);
    return _itermArguments.hasMatch(arguments) &&
        arguments
            .split(';')
            .every(
              (part) =>
                  part.isNotEmpty &&
                  part.contains('=') &&
                  !part.startsWith('='),
            ) &&
        _base64.hasMatch(encoded);
  }

  static bool _isValidSixel(String payload) {
    const prefix = '\x1bPq';
    const suffix = '\x1b\\';
    if (!payload.startsWith(prefix) || !payload.endsWith(suffix)) return false;
    final body = payload.substring(
      prefix.length,
      payload.length - suffix.length,
    );
    if (body.isEmpty) return false;
    for (final codeUnit in body.codeUnits) {
      // Cinder's encoder emits printable seven-bit Sixel syntax only.
      if (codeUnit < 0x20 || codeUnit > 0x7E) return false;
    }
    return true;
  }

  static bool _containsControl(String value) {
    for (final codeUnit in value.codeUnits) {
      if (codeUnit < 0x20 ||
          codeUnit == 0x7F ||
          (codeUnit >= 0x80 && codeUnit <= 0x9F)) {
        return true;
      }
    }
    return false;
  }
}
