import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:cinder_cli/src/commands/create_command.dart';
import 'package:test/test.dart';

void main() {
  test('create command writes a runnable Cinder project', () async {
    final temporaryDirectory = await Directory.systemTemp.createTemp(
      'cinder_cli_create_',
    );
    addTearDown(() => temporaryDirectory.delete(recursive: true));

    final projectDirectory = Directory(
      '${temporaryDirectory.path}${Platform.pathSeparator}sample_app',
    );
    final runner = CommandRunner<int>('cinder', 'Cinder CLI')
      ..addCommand(CreateCommand());

    final result = await runner.run(<String>[
      'create',
      projectDirectory.path,
      '--description',
      'Generated by a CLI test.',
    ]);

    expect(result, 0);
    expect(File('${projectDirectory.path}/pubspec.yaml').existsSync(), isTrue);
    expect(
      File('${projectDirectory.path}/bin/sample_app.dart').existsSync(),
      isTrue,
    );
    expect(
      File('${projectDirectory.path}/test/app_test.dart').existsSync(),
      isTrue,
    );
    expect(
      File('${projectDirectory.path}/pubspec.yaml').readAsStringSync(),
      contains('cinder: ^1.0.0-dev.3'),
    );
  });
}
